name: cavorite

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest, crystal: latest}
          - {os: ubuntu-latest, crystal: nightly}
          - {os: macos-latest}
          - {os: windows-latest}
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2
    - uses: oprypin/install-crystal@v1
      with:
        crystal: 0.36.1
    - run: shards install
    - run: crystal spec -Dpreview_mt
    - run: crystal tool format && git diff --exit-code
      if: matrix.crystal == 'latest'